### PR TITLE
Add required DEFAULT_MATCHER to readme

### PR DESCRIPTION
**Pull request by justjamesdev**

### CODE REVIEW

**Comment by dvshur** [comment]
Hello, please base all the branches from `develop`, not `master`. `master` is the release branch to which `develop` gets merged afterwards.

**Comment by dvshur** [comment]
We appreciate the PR though, thank you for contributing!

**Comment by dvshur** [comment]
Something strange is going on with the Github. It shows too many commits in the diff, ones that have already been merged.

**Comment by justjamesdev** [comment]
Weird, I'll close this and re-submit

**Pull request closed without merging**
